version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1

    networks:
      - postgres_default

networks:
  postgres_default:
    external: true
    name: postgres_default