version: '3.8'

services:
  web:
    build: .
    ports:
      - "5005:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1

    networks:
      - neura_django

networks:
  neura_django:
    external: true
    name: neura_django